# -*- coding: utf-8 -*-
"""Government API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OOsuhsOSjgggABIn3MnEte7BJsKYn4eq
"""

import requests
from pprint import pprint
import matplotlib.pyplot as plt

def SearchProject(keyword_search='เรือดำน้ำ'):

    url='https://opend.data.go.th/govspending/cgdcontract'

    token='VnQkUiuAeERIhLXuCU6nLlGQIJEIF4ru'

    parameters = {'api-key':token,
                  'year':2562,
                  #'keyword':'เรือดำน้ำ'
                  'keyword': keyword_search,
                  'limit': 50
                  }

    r = requests.get(url,params=parameters)
    result = r.json()

    allproject = result['result']

    #print(type(allproject)) #type() คือ การดูชนิดข้อมูล

    print('Count: ',len(allproject)) #len() คือ การนับค่าใน List / Dict
    
    allbudget = []
    projectname = []

    print('---parameter---')
    pprint(allproject[0].keys())
    print('---------------')

    for i in allproject:
      print(i['dept_name'])
      print(i['price_build'])
      print(i['project_name'])
      print(i['province'])
      allbudget.append(int(i['price_build'].replace(',','')))
      projectname.append(i['project_name'])
      print('----')
    print('*****')
    print('ค้นหาคำว่า: {} งบประมาณทั้งหมด: {:,d} บาท'.format(keyword_search,sum(allbudget)))
    print('*****')

    #graph
    xbar = range(len(projectname))
    plt.bar(xbar,allbudget)
    plt.xticks(projectname)
    plt.show()


SearchProject('ไข้หวัด')